### PR TITLE
Refactor SettingsView

### PR DESCRIPTION
**Pull request by MrTimscampi**
Reworks the file to fit better with MVVM and loads bitrates from a JSON file for easier changes.

Some further changes are probably needed to fit properly into the design pattern, but I'd like to move more files to this first, before doing deeper work.

This was tested, but I had to redo the changes on the Xcode project file manually, since Dynatrace keeps erroring out and I had to remove it to compile at all. So, please do re-test it to ensure it works properly.

### CODE REVIEW

**Comment by acvigue** [comment]
Screen Shot 2021-05-25 at 4 05 54 PM

**Comment by MrTimscampi** [comment]
I noticed some edit errors in the project file and fixed them, it should be good to go now 😋

**Comment by acvigue** [comment]
Screen Shot 2021-05-25 at 4 08 19 PM

**Comment by acvigue** [comment]
ContentView.swift:382

**Comment by MrTimscampi** [comment]
Right, I had completely forgotten I did other changes in that file than the Dynatrace stuff 😋

**Comment by acvigue** [comment]
lgtm :)

**Pull request merged**
